{% set version = "2.3.0" %}

package:
  name: openjpeg
  version: {{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v{{ version }}.tar.gz
  sha256: 3dc787c1bb6023ba846c2a0d9b1f6e179f1cd255172bde9eb75b01f1e6c7d71a

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - pkg-config
  host:
    - libtiff >=4.0.8,<4.0.10
    - libpng
    - zlib
  run_exports:
    - libtiff >=4.0.8,<4.0.10
    - libpng
    - zlib

test:
  files:
    - p0_01.j2k
  commands:
    - opj_dump -i p0_01.j2k
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
    home: http://www.openjpeg.org/
    license: BSD 2-Clause
    license_file: LICENSE
    summary: 'An open-source JPEG 2000 codec written in C'

extra:
  recipe-maintainers:
    - ocefpaf
    - gillins
